// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SCV.Data;

#nullable disable

namespace SCV.Data.Migrations
{
    [DbContext(typeof(SportCenterDbContext))]
    [Migration("20250710145125_SeedEvents")]
    partial class SeedEvents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SCV.Data.Models.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("8add11c7-0c60-4776-9ad2-b598fa0f05ae"),
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = new Guid("8d28163a-03ae-4e27-bc00-31d529cd6b52"),
                            Name = "Manager",
                            NormalizedName = "MANAGER"
                        },
                        new
                        {
                            Id = new Guid("e850a970-b0cd-40a1-ad09-4903d92d4d62"),
                            Name = "Trainer",
                            NormalizedName = "TRAINER"
                        },
                        new
                        {
                            Id = new Guid("761adbdb-1d7f-4dbb-8ec1-4d62fd0acde9"),
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("SCV.Data.Models.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasComment("Full name of the user");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("RegisteredOn")
                        .HasColumnType("datetime2")
                        .HasComment("The date the user is register On the site");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", null, t =>
                        {
                            t.HasComment("Application user model that extends IdentityUser");
                        });
                });

            modelBuilder.Entity("SCV.Data.Models.CrossfitClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("CrossFit Class Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2025)
                        .HasColumnType("nvarchar(2025)")
                        .HasComment("CrossFit Class Description for details");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasComment("Indicates if the class is active or not");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasComment("CrossFit Class Name");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasComment("CrossFit Class starting date and time - a string, because it will say in which day of the week will there be classes, ex. Monday 17:00");

                    b.Property<string>("TrainerName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasComment("CrossFit Class Trainer name - can be a Trainer in the Sport Center or a guest Trainer");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("CrossfitClasses", t =>
                        {
                            t.HasComment("CrossFit Class Model");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A high-intensity Hero WOD designed to test endurance and mental toughness.",
                            IsActive = false,
                            Name = "WOD: Hero Workout",
                            StartTime = "Monday at 17:00",
                            TrainerName = "Ivan Dimitrov"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Focus on building strength with heavy lifts and compound movements.",
                            IsActive = false,
                            Name = "CrossFit Strength",
                            StartTime = "Monday at 19:00",
                            TrainerName = "Georgi Kolev"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Enhance flexibility and mobility to improve overall performance.",
                            IsActive = false,
                            Name = "CrossFit Mobility",
                            StartTime = "Tuesday at 18:00",
                            TrainerName = "Maya Ivanova"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Team-based workout to build camaraderie and competitive spirit.",
                            IsActive = false,
                            Name = "CrossFit Team Challenge",
                            StartTime = "Wednesday at 17:00",
                            TrainerName = "Georgi Kolev"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Cardio-focused CrossFit session to build stamina and VO2 max.",
                            IsActive = false,
                            Name = "CrossFit Endurance",
                            StartTime = "Thuesday at 19:00",
                            TrainerName = "Ivan Dimitrov"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Introduction to CrossFit movements and techniques for beginners.",
                            IsActive = false,
                            Name = "CrossFit Basics",
                            StartTime = "Friday at 18:00",
                            TrainerName = "Maya Ivanova"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Specialized training session to prepare for the CrossFit Open competition.",
                            IsActive = false,
                            Name = "CrossFit Open Prep",
                            StartTime = "Saturday at 10:00",
                            TrainerName = "Guest Coach: Stoyan Dimitrov"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Classes teaching technique and power development in snatch and clean and jerk.",
                            IsActive = false,
                            Name = "CrossFit Olympic Lifting",
                            StartTime = "Saturday at 17:00",
                            TrainerName = "Guest Coach: Tsvetan Nikolov"
                        });
                });

            modelBuilder.Entity("SCV.Data.Models.CrossfitClassUser", b =>
                {
                    b.Property<int>("CrossfitClassId")
                        .HasColumnType("int")
                        .HasComment("Foreign key to the referenced CrossfitClass. Part of the entity composite PK.");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Foreign key to the referenced ApplicationUser. Part of the entity composite PK.");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2")
                        .HasComment("The date and time when the user joined the class");

                    b.HasKey("CrossfitClassId", "ApplicationUserId");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("CrossfitClassUsers", t =>
                        {
                            t.HasComment("Represents a many-to-many relationship between ApplicationUser and CrossfitClass.");
                        });
                });

            modelBuilder.Entity("SCV.Data.Models.CrossfitWorkoutOfTheDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Primary key for the workout of the day");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DescriptionHTML")
                        .IsRequired()
                        .HasMaxLength(5025)
                        .HasColumnType("nvarchar(max)")
                        .HasComment("HTML formatted description of the workout of the day");

                    b.Property<string>("DescriptionPlain")
                        .IsRequired()
                        .HasMaxLength(4025)
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Plain text description of the workout of the day");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasComment("Name of the workout of the day - will contain part of the WorkoutDate");

                    b.Property<DateTime>("WorkoutDate")
                        .HasColumnType("datetime2")
                        .HasComment("Date when the workout of the day is scheduled");

                    b.HasKey("Id");

                    b.ToTable("CrossfitWorkoutOfTheDays", t =>
                        {
                            t.HasComment("Represents a Crossfit Workout of the Day (WOD)");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DescriptionHTML = "<p><strong>Triple Deuce</strong></p><p>As many rounds and reps as possible in 20 minutes of:<br>22 burpees<br>22 air squats<br>22 pull-ups<br>22 sandbag ground-to-over-the-shoulders<br>722-meter run</p>...",
                            DescriptionPlain = "Triple Deuce\n\nAs many rounds and reps as possible in 20 minutes of:\n22 burpees\n22 air squats\n22 pull-ups\n22 sandbag ground-to-over-the-shoulders\n722-meter run\n\n♀ 40-lb sandbag\n♂ 60-lb sandbag\n\nPost rounds and reps to comments.\n\nArmy Sgt. 1st Class Jamie Nicholas...",
                            Name = "Friday/250704",
                            WorkoutDate = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            DescriptionHTML = "<p>5 rounds, each for time, of:<br>500-meter row</p><p>Rest 3 minutes between efforts.</p><p>Post times to the comments.</p>...",
                            DescriptionPlain = "5 rounds, each for time, of:\n500-meter row\n\nRest 3 minutes between efforts.\n\nPost times to the comments.\n\nStimulus and Strategy:\nToday’s workout consists of 5 all-out sprints on the rower...",
                            Name = "Saturday/250705",
                            WorkoutDate = new DateTime(2025, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            DescriptionHTML = "<p><strong>Rest Day</strong></p><p><a href=\"https://youtu.be/aqHQ6hpiXdk\">Why We Plateau and How to Overcome It</a></p>...",
                            DescriptionPlain = "Rest Day\n\nWhy We Plateau and How to Overcome It\n\nJoin CrossFit coaches Eric O'Connor and Pat Barber as they break down the real reasons athletes hit plateaus and the proven strategies to push past them...",
                            Name = "Sunday/250706",
                            WorkoutDate = new DateTime(2025, 7, 6, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("SCV.Data.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Primary Key for the event");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(525)
                        .HasColumnType("nvarchar(525)")
                        .HasComment("Detailed description of the event, e.g., 'A local competition for intermediate-level CrossFitters.'");

                    b.Property<int>("EventType")
                        .HasColumnType("int")
                        .HasComment("Type of the event - Fitness, CrossFit, Powerlifting");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasComment("URL of the event image");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("Indicates if the event is deleted (soft delete)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(85)
                        .HasColumnType("nvarchar(85)")
                        .HasComment("Location of the event, e.g., 'Sport Center Victory - Ruse'");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasComment("Start date and time of the event");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasComment("Title of the event, e.g., 'CrossFit Regional Challenge'");

                    b.HasKey("Id");

                    b.ToTable("Events", t =>
                        {
                            t.HasComment("Represents an event in the web application, such as a fitness, crossfit or powerlifting competition or training session.");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "6-week transformation bootcamp with professional trainers and nutritionists.",
                            EventType = 0,
                            ImageUrl = "/events/fitnessTransformation.jpg",
                            IsDeleted = false,
                            Location = "Sport Center Victory - Ruse",
                            StartDate = new DateTime(2025, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Fitness Transformation Bootcamp"
                        },
                        new
                        {
                            Id = 2,
                            Description = "A weekend retreat focusing on yoga, meditation, and wellness on the beach.",
                            EventType = 0,
                            ImageUrl = "/events/fitnessYoga.jpg",
                            IsDeleted = false,
                            Location = "Sport Center Victory - Ruse",
                            StartDate = new DateTime(2025, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Yoga Retreat Weekend"
                        },
                        new
                        {
                            Id = 3,
                            Description = "A local competition for intermediate-level CrossFitters.",
                            EventType = 1,
                            ImageUrl = "/events/crossFitRegional.jpg",
                            IsDeleted = false,
                            Location = "Sport Center Victory - Ruse",
                            StartDate = new DateTime(2025, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "CrossFit Regional Challenge"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Try a real CrossFit Open WOD with the community and judges.",
                            EventType = 1,
                            ImageUrl = "/events/crossFitOpenNight.jpg",
                            IsDeleted = false,
                            Location = "Sport Center Victory - Ruse",
                            StartDate = new DateTime(2025, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "CrossFit Open Night"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Open bench press meet-up for all strength levels.",
                            EventType = 2,
                            ImageUrl = "/events/powerliftingBenchpress.png",
                            IsDeleted = false,
                            Location = "Sport Center Victory - Ruse",
                            StartDate = new DateTime(2025, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Bench Press Meet-Up"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Hands-on technique workshop on snatch and clean & jerk.",
                            EventType = 2,
                            ImageUrl = "/events/powerliftingOlympicLifting.jpg",
                            IsDeleted = false,
                            Location = "Sport Center Victory - Ruse",
                            StartDate = new DateTime(2025, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Olympic Lifting Workshop"
                        });
                });

            modelBuilder.Entity("SCV.Data.Models.EventUser", b =>
                {
                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Foreign key to the referenced ApplicationUser. Part of the entity composite PK.");

                    b.Property<int>("EventId")
                        .HasColumnType("int")
                        .HasComment("Foreign key to the referenced Event. Part of the entity composite PK.");

                    b.HasKey("ApplicationUserId", "EventId");

                    b.HasIndex("EventId");

                    b.ToTable("EventUsers", t =>
                        {
                            t.HasComment("Represents a user who has purchased a membership.");
                        });
                });

            modelBuilder.Entity("SCV.Data.Models.Exercise", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(136)
                        .HasColumnType("nvarchar(136)")
                        .HasComment("Unique identifier for the exercise - the name in snake case will be the Id.");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("Category of the exercise - strength, cardio, flexibility, etc.");

                    b.Property<string>("Equipment")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasComment("Equipment used for the exercise - barbell, dumbbell, bodyweight, etc.");

                    b.Property<string>("Force")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("Type of force applied in the exercise - push, pull, etc.");

                    b.Property<string>("ImageUrlOne")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasComment("URL of the first image representing the exercise, if available..");

                    b.Property<string>("ImageUrlTwo")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasComment("URL of the second image representing the exercise, if available.");

                    b.Property<string>("Instructions")
                        .HasMaxLength(5025)
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Instructions on how to perform the exercise.");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("Indicates whether the exercise is deleted or not - soft deletion.");

                    b.Property<string>("Mechanic")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasComment("Mechanic of the exercise - compound, isolation, etc.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)")
                        .HasComment("Name of the exercise");

                    b.Property<string>("PrimaryMuscles")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComment("Primary muscles targeted by the exercise.");

                    b.Property<string>("SecondaryMuscles")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComment("Secondary muscles targeted by the exercise, if any.");

                    b.HasKey("Id");

                    b.ToTable("Exercises", t =>
                        {
                            t.HasComment("Represents an exercise in the database for the web app.");
                        });
                });

            modelBuilder.Entity("SCV.Data.Models.Membership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Primary Key for the membership.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(525)
                        .HasColumnType("nvarchar(525)")
                        .HasComment("Description of the membership.");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasComment("Duration of the membership - '1 month', '3 months', '1 year'.");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("Indicates whether the membership is deleted.");

                    b.Property<int>("MembershipTier")
                        .HasColumnType("int")
                        .HasComment("Tier of the membership - FitnessStandard, CrossFitUnlimited, PowerliftingBeginners and et.");

                    b.Property<int>("MembershipType")
                        .HasColumnType("int")
                        .HasComment("Type of the membership - Fitness, CrossFit, Powerlifting.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Name of the membership");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 6)")
                        .HasComment("Price of the membership.");

                    b.Property<Guid?>("TrainerId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Foreign Key to the Trainer, who coaches in the membership. If null the membership is a class.");

                    b.HasKey("Id");

                    b.HasIndex("TrainerId");

                    b.ToTable("Memberships", t =>
                        {
                            t.HasComment("Represents a membership in the web application, for the fitness, crossfit and powerlifting.");
                        });
                });

            modelBuilder.Entity("SCV.Data.Models.MembershipUser", b =>
                {
                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Foreign key to the referenced ApplicationUser. Part of the entity composite PK.");

                    b.Property<int>("MembershipId")
                        .HasColumnType("int")
                        .HasComment("Foreign key to the referenced Membership. Part of the entity composite PK.");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("Indicates whether the membership user is deleted. Used for soft deletion.");

                    b.Property<DateTime>("PurchasedOn")
                        .HasColumnType("datetime2")
                        .HasComment("The date and time when the membership was purchased.");

                    b.HasKey("ApplicationUserId", "MembershipId");

                    b.HasIndex("MembershipId");

                    b.ToTable("MembershipUsers", t =>
                        {
                            t.HasComment("Represents a user who has purchased a membership.");
                        });
                });

            modelBuilder.Entity("SCV.Data.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Unique identifier for the order");

                    b.Property<Guid?>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identifier of the customer who made the order");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("Flag which is used for soft deletion");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2")
                        .HasComment("The day in which the order was made");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("int")
                        .HasComment("Shows what is the status of the order - ");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int")
                        .HasComment("Shows the method of payment");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18, 6)")
                        .HasComment("The total price of the order");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("SCV.Data.Models.OrderProduct", b =>
                {
                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Foreign key to the referenced Order. Part of the entity composite PK.");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Foreign key to the referenced Product. Part of the entity composite PK.");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 6)")
                        .HasComment("Price per single unit");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasComment("The quantity of the product");

                    b.HasKey("OrderId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderProducts", t =>
                        {
                            t.HasComment("Represents an item in an order, linking a product to an order with quantity and price details");
                        });
                });

            modelBuilder.Entity("SCV.Data.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Primary Key for the product.");

                    b.Property<string>("Description")
                        .HasMaxLength(525)
                        .HasColumnType("nvarchar(525)")
                        .HasComment("Description of the product, providing details about its features and benefits.");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasComment("URL of the product image, used for displaying the product in the UI.");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("Indicates if the product is currently available for purchase. If true, the product is deleted and not available.");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 6)")
                        .HasComment("Price of the product");

                    b.Property<int>("ProductCategory")
                        .HasColumnType("int")
                        .HasComment("Category of the product - 'Equipment' or 'Nutrition'.");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasComment("Quantity of the product available in stock.");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("Title of the product, e.g., 'Weightlifting Belt'.");

                    b.HasKey("Id");

                    b.ToTable("Products", t =>
                        {
                            t.HasComment("Represents a product in the web application. Can be an Equipment or a Nutrition product.");
                        });
                });

            modelBuilder.Entity("SCV.Data.Models.Trainer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Primary key for the Trainer entity.");

                    b.Property<Guid?>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Foreign key so that the user can be identify as a trainer/coach.");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(525)
                        .HasColumnType("nvarchar(525)")
                        .HasComment("Short biography of the trainer, describing their experience and qualifications.");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)")
                        .HasComment("Email address of the trainer. Must be unique.");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasComment("First name of the trainer.");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasComment("URL of the trainer's profile image. Optional, can be null.");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("Indicates whether the trainer is marked as deleted. Used for soft deletion.");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasComment("Last name of the trainer.");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasComment("Phone number of the trainer. Optional, can be null.");

                    b.Property<int>("TrainerSpecialty")
                        .HasColumnType("int")
                        .HasComment("Specialty of the trainer, indicating their area of expertise (e.g., Fitness, CrossFit, Powerlifting).");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("Trainers", t =>
                        {
                            t.HasComment("Represents a personal trainer in the web application. Can be a fitness, crossfit or powerlifting trainer/coach.");
                        });
                });

            modelBuilder.Entity("SCV.Data.Models.TrainerUser", b =>
                {
                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Foreign key to the referenced ApplicationUser. Part of the entity composite PK.");

                    b.Property<Guid>("TrainerId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Foreign key to the referenced Trainer. Part of the entity composite PK.");

                    b.Property<string>("AdditionalInformation")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("Additional information about which course/membership/plan is the user attached to the trainer");

                    b.HasKey("ApplicationUserId", "TrainerId");

                    b.HasIndex("TrainerId");

                    b.ToTable("TrainerUsers", t =>
                        {
                            t.HasComment("Entity representing the many-to-many relationship between ApplicationUser and Trainer.");
                        });
                });

            modelBuilder.Entity("SCV.Data.Models.UserFeedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Primary key for the UserFeedback Table.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Feedback")
                        .IsRequired()
                        .HasMaxLength(2024)
                        .HasColumnType("nvarchar(2024)")
                        .HasComment("The context of the feedback.");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasComment("The URL of the image associated with the feedback, if any.");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasComment("The status of the feedback, indicating whether it is pending, publish, or removed. The default will be pending.");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("The Foreign key to the User how added the feedback");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("The name of the user who provided the feedback.");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserFeedbacks", t =>
                        {
                            t.HasComment("Represents user feedback in the system.");
                        });
                });

            modelBuilder.Entity("SCV.Data.Models.WorkoutPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Primary key for the workout plan");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2025)
                        .HasColumnType("nvarchar(2025)")
                        .HasComment("Description of the workout plan");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasComment("Optional image URL for the workout plan");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("Indicates if the workout plan is currently active or deleted");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasComment("Title of the workout plan, e.g., 'Push/Pull/Legs'");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasComment("Type of the workout plan - 'CrossFit', 'Powerlifting', 'Bodybuilding'");

                    b.HasKey("Id");

                    b.ToTable("WorkoutPlans", t =>
                        {
                            t.HasComment("Workout Plan entity for a structured workout plan for fitness, crossFit or powerlifting");
                        });
                });

            modelBuilder.Entity("SCV.Data.Models.WorkoutPlanExercise", b =>
                {
                    b.Property<string>("ExerciseId")
                        .HasColumnType("nvarchar(136)")
                        .HasComment("Foreign key to the referenced Exercise. Part of the entity composite PK.");

                    b.Property<int>("WorkoutPlanId")
                        .HasColumnType("int")
                        .HasComment("Foreign key to the referenced WorkoutPlan. Part of the entity composite PK.");

                    b.HasKey("ExerciseId", "WorkoutPlanId");

                    b.HasIndex("WorkoutPlanId");

                    b.ToTable("WorkoutPlanExercises", t =>
                        {
                            t.HasComment("Workout Plan Exercise entity representing an exercise within a workout plan");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("SCV.Data.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("SCV.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("SCV.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("SCV.Data.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SCV.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("SCV.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SCV.Data.Models.CrossfitClass", b =>
                {
                    b.HasOne("SCV.Data.Models.ApplicationUser", null)
                        .WithMany("CrossfitClassesUsers")
                        .HasForeignKey("ApplicationUserId");
                });

            modelBuilder.Entity("SCV.Data.Models.CrossfitClassUser", b =>
                {
                    b.HasOne("SCV.Data.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SCV.Data.Models.CrossfitClass", "CrossfitClass")
                        .WithMany("CrossfitClassUsers")
                        .HasForeignKey("CrossfitClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("CrossfitClass");
                });

            modelBuilder.Entity("SCV.Data.Models.EventUser", b =>
                {
                    b.HasOne("SCV.Data.Models.ApplicationUser", "ApplicationUser")
                        .WithMany("EventUsers")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SCV.Data.Models.Event", "Event")
                        .WithMany("EventUsers")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("SCV.Data.Models.Membership", b =>
                {
                    b.HasOne("SCV.Data.Models.Trainer", "Trainer")
                        .WithMany("Memberships")
                        .HasForeignKey("TrainerId");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("SCV.Data.Models.MembershipUser", b =>
                {
                    b.HasOne("SCV.Data.Models.ApplicationUser", "ApplicationUser")
                        .WithMany("MembershipUsers")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SCV.Data.Models.Membership", "Membership")
                        .WithMany("MembershipUsers")
                        .HasForeignKey("MembershipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Membership");
                });

            modelBuilder.Entity("SCV.Data.Models.Order", b =>
                {
                    b.HasOne("SCV.Data.Models.ApplicationUser", null)
                        .WithMany("Orders")
                        .HasForeignKey("ApplicationUserId");

                    b.HasOne("SCV.Data.Models.ApplicationUser", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("SCV.Data.Models.OrderProduct", b =>
                {
                    b.HasOne("SCV.Data.Models.Order", "Order")
                        .WithMany("OrderProducts")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SCV.Data.Models.Product", "Product")
                        .WithMany("OrderProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SCV.Data.Models.Trainer", b =>
                {
                    b.HasOne("SCV.Data.Models.ApplicationUser", "ApplicationUser")
                        .WithMany("Trainers")
                        .HasForeignKey("ApplicationUserId");

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("SCV.Data.Models.TrainerUser", b =>
                {
                    b.HasOne("SCV.Data.Models.ApplicationUser", "ApplicationUser")
                        .WithMany("TrainerUsers")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SCV.Data.Models.Trainer", "Trainer")
                        .WithMany("TrainerUsers")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("SCV.Data.Models.UserFeedback", b =>
                {
                    b.HasOne("SCV.Data.Models.ApplicationUser", null)
                        .WithMany("UserFeedbacks")
                        .HasForeignKey("ApplicationUserId");

                    b.HasOne("SCV.Data.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SCV.Data.Models.WorkoutPlanExercise", b =>
                {
                    b.HasOne("SCV.Data.Models.Exercise", "Exercise")
                        .WithMany("WorkoutPlanExercises")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SCV.Data.Models.WorkoutPlan", "WorkoutPlan")
                        .WithMany("WorkoutPlanExercises")
                        .HasForeignKey("WorkoutPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("WorkoutPlan");
                });

            modelBuilder.Entity("SCV.Data.Models.ApplicationUser", b =>
                {
                    b.Navigation("CrossfitClassesUsers");

                    b.Navigation("EventUsers");

                    b.Navigation("MembershipUsers");

                    b.Navigation("Orders");

                    b.Navigation("TrainerUsers");

                    b.Navigation("Trainers");

                    b.Navigation("UserFeedbacks");
                });

            modelBuilder.Entity("SCV.Data.Models.CrossfitClass", b =>
                {
                    b.Navigation("CrossfitClassUsers");
                });

            modelBuilder.Entity("SCV.Data.Models.Event", b =>
                {
                    b.Navigation("EventUsers");
                });

            modelBuilder.Entity("SCV.Data.Models.Exercise", b =>
                {
                    b.Navigation("WorkoutPlanExercises");
                });

            modelBuilder.Entity("SCV.Data.Models.Membership", b =>
                {
                    b.Navigation("MembershipUsers");
                });

            modelBuilder.Entity("SCV.Data.Models.Order", b =>
                {
                    b.Navigation("OrderProducts");
                });

            modelBuilder.Entity("SCV.Data.Models.Product", b =>
                {
                    b.Navigation("OrderProducts");
                });

            modelBuilder.Entity("SCV.Data.Models.Trainer", b =>
                {
                    b.Navigation("Memberships");

                    b.Navigation("TrainerUsers");
                });

            modelBuilder.Entity("SCV.Data.Models.WorkoutPlan", b =>
                {
                    b.Navigation("WorkoutPlanExercises");
                });
#pragma warning restore 612, 618
        }
    }
}
