<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SCV.Data\SCV.Data.csproj" />
    <ProjectReference Include="..\SCV.GlCommon\SCV.GlCommon.csproj" />
    <ProjectReference Include="..\SCV.Data.Models\SCV.Data.Models.csproj" />
    <ProjectReference Include="..\SCV.Services.AutoMapper\SCV.Services.AutoMapper.csproj" />
    <ProjectReference Include="..\SCV.Services.Common\SCV.Services.Common.csproj" />
    <ProjectReference Include="..\SCV.Web.ViewModels\SCV.Web.ViewModels.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="HtmlAgilityPack" Version="1.12.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
  </ItemGroup>

</Project>
